### ISSUE TITLE
[Android] Crash onRequest interceptor when options.baseUrl is empty

### ISSUE THREAD

**Issue by HadesPTIT** [diefferson/http_certificate_pinning#38]
```

Fatal Exception: java.net.MalformedURLException: no protocol: 
       at java.net.URL.<init>(URL.java:601)
       at java.net.URL.<init>(URL.java:498)
       at java.net.URL.<init>(URL.java:447)
       at diefferson.http_certificate_pinning.HttpCertificatePinningPlugin.getFingerprint(HttpCertificatePinningPlugin.kt:98)
       at diefferson.http_certificate_pinning.HttpCertificatePinningPlugin.checkConnexion(HttpCertificatePinningPlugin.kt:91)
       at diefferson.http_certificate_pinning.HttpCertificatePinningPlugin.handleCheckEvent(HttpCertificatePinningPlugin.kt:77)
       at diefferson.http_certificate_pinning.HttpCertificatePinningPlugin.onMethodCall$lambda-0(HttpCertificatePinningPlugin.kt:56)
       at diefferson.http_certificate_pinning.HttpCertificatePinningPlugin.lambda$tmYn8PAfUzdgAXWVDtDvHyTq2BQ(HttpCertificatePinningPlugin.kt)
       at diefferson.http_certificate_pinning.-$$Lambda$HttpCertificatePinningPlugin$tmYn8PAfUzdgAXWVDtDvHyTq2BQ.run(lambda:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by diefferson** [comment]
Fixed on release 2.1.1
